# Generated by Django 4.0.3 on 2022-03-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('precinct', models.CharField(max_length=250)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.barangay')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.province'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.city'),
        ),
    ]
