# Generated by Django 4.0.3 on 2022-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='role',
            field=models.CharField(default='Poll Watcher', max_length=250),
        ),
    ]
